export const gridprops = {
  swap: {
    p1: "Swap",
    p2: "Peer to peer marketplace",
    p3: "Do you worry about unfavourable exchange rates when sending money? Create or accept offers at your preferred rate on Bomba's Peer to peer marketplace. ",
    p4: "Swap now",
    imgsrc: "/P2P.svg",
    imgalt: "P2P Market.svg",
    grid_h: "43.75rem",
    grid_bgcolor: "rgba(109, 72, 255, 0.1)",
    coming_soon: "none",
  },
  express: {
    p1: "Express",
    p2: "Take the express lane",
    p3: "Transact with light speed using Bomba Express. You can send funds at Bomba’s exchange rates to family and friends from the UK & US to 20 African countries.",
    p4: "Send now",
    imgsrc: "/Express.svg",
    imgalt: "Express.svg",
    grid_h: "50rem",
    grid_bgcolor: "rgba(4, 206, 157, 0.1)",
    coming_soon: "none",
  },
  refer: {
    p1: "Refer & Earn",
    p2: "Make money while you refer",
    p3: "Bomba allows you to earn passively through its platform. Refer your friends and family to use Bomba and earn up to £140",
    p4: "Share now",
    imgsrc: "/Referral.svg",
    imgalt: "Referral.svg",
    grid_h: "50rem",
    grid_bgcolor: "rgba(110, 128, 163, 0.1)",
    coming_soon: "none",
  },
  connect: {
    p1: "Bomba Connect",
    p2: "Deals from top brands ",
    p3: "With Bomba Connect, you can pay for and access goods and services from some of the best and trusted brands - at the best rates and with minimal wait time - all within the Bomba App.",
    p4: "Explore now",
    imgsrc: "/Kyshi Connect.svg",
    imgalt: "Kyshi Connect.svg",
    grid_h: "43.75rem",
    grid_bgcolor: "rgba(239, 132, 92, 0.1)",
    coming_soon: "block",
  },
};
